### ISSUE TITLE
Multicurrency withdrawal

### ISSUE THREAD

**Issue by adontz** [coilhq/tigerbeetle#39]
Imagine I have a multicurrency account and my balances are 100 USD and 100 EUR.
If I try to pay 150 USD, most systems will be smart enough to withdraw 100 USD and 42 EUR (~50USD) leaving me with 0 USD and 58 EUR balance. On the other hand if try to pay 150 EUR, most systems will be smart enough to withdraw 100 EUR and 59 USD (~50EUR) leaving me with 41 USD and 0 EUR balance. 

How can I implement this logic with tigerbettle in an atomic manner?

**Comment by jorangreef** [comment]
Thanks for the question @adontz.

How you split the amounts in your transfers between accounts are at your discretion, so you would determine how you want your system to split the difference between currencies and then TigerBeetle would record that for you.

TigerBeetle would enforce these invariants for you:

* transfers are only between accounts with the same unit of value (i.e. currency).
* transfers may be linked together to succeed or fail atomically (so you could have one transfer going against the USD account, and another going against the EUR account to pull off what you want to achieve).

**Comment by adontz** [comment]
> How you split the amounts in your transfers between accounts are at your discretion, so you would determine how you want your system to split the difference between currencies and then TigerBeetle would record that for you.

I cannot determine this, because generally speaking I do not know balances. Thus withdrawal cannot be atomic, it will be classic race condition.

-    100 EUR   100 USD;    Initial state of the customer
-    100 EUR   100 USD;    I select balances of the customer, they are 100 EUR, 100 USD
-    200 EUR   100 USD;    Someone transfers 100 EUR to the customer
-    100 EUR    41 USD;    I withdraw 150 EUR which I split into 100 EUR and 59 USD because I believe balances are 100 EUR, 100 USD
-    100 EUR    41 USD;    Customer is shocked I have converted USD, while there was enough EUR

**Comment by jorangreef** [comment]
Ah, forgot to mention that TigerBeetle would enforce not overdrawing the available liquidity in an account.

We also have something in the works where you could transfer what is available, but up to a limit.

These are primitives that could help.

We wanted to keep the complexity of currency conversions out of TigerBeetle.

**Comment by adontz** [comment]
I still do not get how can I achieve my goal in an atomic way.

**Comment by HugoFlorentino** [comment]
Neither the Accounts struct nor the Transfer struct have a field for currency as far as I can see, so unless I am mistaken, you should probably perform a batch of 2 operations.

Even in a logical level you perceive a multi-currency account as a single account, if currencies are separated you re actually using separate accounts at the database layer, even though you might refer to them by the same account number only with different currency.

**Comment by HugoFlorentino** [comment]
Having said this, it would be good having a dedicated field for currency, that way preventing accidental mixing of different currencies would be simpler, IMHO.

**Comment by adontz** [comment]
Field for a currency is not the point of my question at all and batch of two operations does not solve my problem at all, not even near. I am happy to answer any questions regarding the original problem.

**Comment by HugoFlorentino** [comment]
> 
> 
> Field for a currency is not the point of my question at all and batch of two operations does not solve my problem at all, not even near. I am happy to answer any questions regarding the original problem.

Aren't the `two_fase_commit` and `linked` flags supposed to guarantee the atomicity of operation on two linked transfers?
