### ISSUE TITLE
Reached unreachable code

### ISSUE THREAD

**Issue by batiati** [coilhq/tigerbeetle#59]
Hi folks,
I got a ```Reached unreachable code``` panic, running ```benchmark.zig``` twice against the same server.

## Steps to reproduce

1) Build tigerbeetle from sources, and access ```zig-output/bin```
1) Run ```./tigerbeetle init --cluster=0 --replica=0 --directory=.```
2) Run ```./tigerbeetle start --cluster=0 --replica=0 --directory=. --addresses=127.0.0.1:3001```
3) In another terminal, run ```zig run -OReleaseSafe ./src/benchmark.zig``` *twice*.
The first time it runs OK, but the second time the server crashes.

benchmark's output:

```bash
batiati@TSIBATIATI:~/tigerbeetle$ zig run -OReleaseSafe ./src/benchmark.zig
creating accounts...
batching transfers...
starting benchmark...
============================================
531914 transfers per second

create_transfers max p100 latency per 5000 transfers = 23ms
commit_transfers max p100 latency per 5000 transfers = 0ms
batiati@TSIBATIATI:~/tigerbeetle$ zig run -OReleaseSafe ./src/benchmark.zig
creating accounts...
batching transfers...
starting benchmark...
error(message_bus): error connecting to replica 0: error.ConnectionRefused
error(message_bus): error connecting to replica 0: error.ConnectionRefused
error(message_bus): error connecting to replica 0: error.ConnectionRefused
^C
```

Server's output (running Release-Safe)

```
info(storage): opening "cluster_0000000000_replica_000.tigerbeetle"...
info: cluster=0 replica=0: listening on 0.0.0.0:3001
info(message_bus): connection from client 55741322461856235128456485717824778813
info(message_bus): peer performed an orderly shutdown: message_bus.union:392:19{ .client = 55741322461856235128456485717824778813 }
info(message_bus): connection from client 305270733519922419579078604465720248410
thread 962 panic: reached unreachable code
Aborted
```

Server's output (running in Debug)

```
info(message_bus): connection from client 137357130890439269904175630134727826053
thread 911 panic: reached unreachable code
/home/batiati/zig/lib/std/debug.zig:226:14: 0x222ddb in std.debug.assert (tigerbeetle)
    if (!ok) unreachable; // assertion failure
             ^
/home/batiati/tigerbeetle/src/vsr/journal.zig:861:19: 0x29793c in vsr.journal.Journal(vsr.replica.Replica(state_machine.StateMachine,message_bus.MessageBusImpl(message_bus.ProcessType.replica),storage.Storage,time.Time),storage.Storage).write_prepare (tigerbeetle)
            assert(message.header.offset + sectors.len <= self.size_circular_buffer);
                  ^
/home/batiati/tigerbeetle/src/vsr/replica.zig:4226:39: 0x28825a in vsr.replica.Replica(state_machine.StateMachine,message_bus.MessageBusImpl(message_bus.ProcessType.replica),storage.Storage,time.Time).write_prepare (tigerbeetle)
            self.journal.write_prepare(write_prepare_on_write, message, trigger);
                                      ^
/home/batiati/tigerbeetle/src/vsr/replica.zig:1680:31: 0x278ebe in vsr.replica.Replica(state_machine.StateMachine,message_bus.MessageBusImpl(message_bus.ProcessType.replica),storage.Storage,time.Time).append (tigerbeetle)
            self.write_prepare(message, .append);
                              ^
/home/batiati/tigerbeetle/src/vsr/replica.zig:712:24: 0x268675 in vsr.replica.Replica(state_machine.StateMachine,message_bus.MessageBusImpl(message_bus.ProcessType.replica),storage.Storage,time.Time).on_prepare (tigerbeetle)
            self.append(message);
                       ^
```
## Notes

- Reproduced using Linux Ubuntu 5.11.0-38-generic x86_64 GNU/Linux

- Running using ```scripts/benchmark.sh``` works fine because the cluster is initialized every execution.

I'm not sure if the benchmark is supposed to run multiple times against the same cluster. It's most likely I'm doing something wrong, but I didn't expect a server panic.

**Comment by jorangreef** [comment]
Thanks for the detailed issue @batiati !

The benchmark is only supposed to be run once per cluster, that's why the benchmark script reinitializes the cluster each time, because otherwise transfers would be duplicated, instead of measuring first-time inserts.

The reason for the panic here though is because the circular buffer journal is wrapping around. We are busy implementing our snapshotting at the moment to allow the circular buffer to wrap but at present we panic on that assertion you got.

The fixed size journal limit will be lifted as soon as snapshotting our state machine is completed.

**Comment by batiati** [comment]
That's fine! Thank you.
