### ISSUE TITLE
Add support for `lookup_transfers`

### ISSUE THREAD

**Issue by koekiebox** [coilhq/tigerbeetle#63]
TigerBeetle currently supports the following operations;
* `create_accounts`
* `create_transfers`
* `commit_transfers`
* `lookup_accounts`

There is a requirement to lookup an existing transfer via id (`lookup_transfers(u128`).
Although the `state_machine` already supports transfer lookups via `get_transfer`, the operation is not exposed.

Furthermore the https://github.com/coilhq/tigerbeetle-node repo needs to be updated to support transfer retrieval.

**Comment by koekiebox** [comment]
PR's for Issue;
https://github.com/coilhq/tigerbeetle/pull/64
https://github.com/coilhq/tigerbeetle-node/pull/21

**Comment by jorangreef** [comment]
Thanks @koekiebox awesome to have this done already.
